export const BODY: string = 'Body'
export const PROFILE: string = 'Profile'
export const HEALTH_JOURNEY: string = 'Health Journey'
export const WELLNESS: string = 'Wellness'
export const RECIPES: string = 'Recipes'
export const SIGN_OUT: string = 'Sign Out'
