export const BODY: string = 'Body'
export const FITNESS: string = 'Fitness'
export const PROFILE: string = 'Profile'
export const HEALTH_JOURNEY: string = 'Health Journey'
export const MIND_WELLNESS: string = 'Mind'
export const RECIPES: string = 'Diet'
export const VITA_BOT: string = 'VitaBot'
export const SIGN_OUT: string = 'Sign Out'
